# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build
on:
  push:
    branches:
      - main
    paths:
      - 'gradle/**'
      - 'api/**'
      - 'example-plugin/**'
      - 'build.gradle.kts'
      - 'settings.gradle.kts'
      - 'gradlew'
      - 'gradlew.bat'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[no-build]')"
    steps:
      - uses: "actions/checkout@v3.1.0"
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 8
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Test with Gradle
        run: ./gradlew test
      - name: Build jar with Gradle
        run: ./gradlew build
      - name: Upload API artifacts
        uses: "actions/upload-artifact@v3.1.1"
        with:
          name: AnnoyingAPI
          path: api/build/libs
      - name: Upload Example artifacts
        uses: "actions/upload-artifact@v3.1.1"
        with:
          name: AnnoyingExample
          path: example-plugin/build/libs
